# Generated by Django 5.0.3 on 2024-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('apiKey', models.CharField(max_length=500)),
                ('nbOfAvailableRequests', models.IntegerField()),
                ('nbUsedRequests', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('adminKey', models.CharField(max_length=500)),
            ],
        ),
    ]
