# Generated by Django 5.0.3 on 2024-10-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApi', '0003_client_createdat_platform_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
