# Generated by Django 5.0.3 on 2024-10-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApi', '0004_remove_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='hey@mail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='nbUsedRequests',
            field=models.IntegerField(default=0),
        ),
    ]
