# Generated by Django 5.0.3 on 2024-10-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApi', '0005_client_email_alter_client_nbusedrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='platform',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='workshopApi.platform'),
            preserve_default=False,
        ),
    ]
